// ============================================
//  SnackTrack — App Data
//  Stores, food items, and menu listings
// ============================================

const STORES = {
  hrb: {
    id: 'hrb',
    name: 'Healthy Rice Bowlz',
    title: 'Healthy\nRice Bowlz',
    tag: 'Salads & Bowls',
    rating: '4.8',
    wait: '10 min',
    open: true,
    desc: 'Specializing in fresh, nutrient-dense ingredients. Our menus are designed in collaboration with campus nutritionists.',
    emoji: '🥗',
    donut: 'conic-gradient(var(--primary) 0deg 126deg, #22C55E 126deg 252deg, #1E293B 252deg 360deg)',
    donutLegend: [['var(--primary)', 'Protein'], ['#22C55E', 'Carbs'], ['#1E293B', 'Fats']],
    stats: [
      ['🥗 Veggie Options', '65%'],
      ['🔥 Avg. Calories', '480 kcal'],
      ['🎯 Best for', 'Muscle Gain', '#DCFCE7', '#15803D'],
    ],
    quote: '"Students love this store for high-protein options after morning workouts."',
    tabs: ['All Items', 'High Protein', 'Vegetarian', 'Under 500 Cal', 'Budget Friendly'],
    items: ['quinoa', 'chicken', 'med', 'tofu', 'steak', 'salmon'],
    persIcon: '✨',
    persTitle: 'Personalize Your Goals',
    persDesc: "We can highlight items based on your specific macros and allergies. Update your profile to get smart recommendations.",
    persBtnTxt: 'Update Nutrition Profile',
  },

  pp: {
    id: 'pp',
    name: 'Protein Palace',
    title: 'Protein\nPalace',
    tag: 'Grills & Meat',
    rating: '4.5',
    wait: '15 min',
    open: true,
    desc: 'The ultimate stop for athletes. High protein meals designed to fuel your workouts and aid recovery.',
    emoji: '🥩',
    donut: 'conic-gradient(var(--primary) 0deg 180deg, #F59E0B 180deg 270deg, #1E293B 270deg 360deg)',
    donutLegend: [['var(--primary)', 'Protein'], ['#F59E0B', 'Fats'], ['#1E293B', 'Carbs']],
    stats: [
      ['💪 Avg. Protein', '38g'],
      ['🔥 Avg. Calories', '520 kcal'],
      ['🎯 Best for', 'Muscle Gain', '#FEF3C7', '#B45309'],
    ],
    quote: '"Best high-protein post-workout meals on campus."',
    tabs: ['All Items', 'High Protein', 'Muscle Gain', 'Recovery'],
    items: ['steak', 'chicken', 'salmon', 'tofu', 'quinoa', 'eggs'],
    persIcon: '💪',
    persTitle: 'Optimize Your Gains',
    persDesc: "Set your fitness goals and we'll highlight the best meals for your muscle-building journey.",
    persBtnTxt: 'Set Fitness Goals',
  },

  ww: {
    id: 'ww',
    name: 'Wok Wonders',
    title: 'Wok\nWonders',
    tag: 'Asian Fusion',
    rating: '4.2',
    wait: null,
    open: false,
    desc: 'Authentic flavors from across Asia, prepared fresh with vibrant vegetables.',
    emoji: '🍜',
  },

  dd: {
    id: 'dd',
    name: 'Daily Deli',
    title: 'Daily\nDeli',
    tag: 'Sandwiches',
    rating: '4.0',
    wait: null,
    open: false,
    desc: 'Classic deli sandwiches and artisan wraps for the student on the go.',
    emoji: '🥪',
  },

  pasta: {
    id: 'pasta',
    name: 'Pasta Point',
    title: 'Pasta\nPoint',
    tag: 'Italian',
    rating: '4.6',
    wait: '12 min',
    open: true,
    desc: 'Hand-stretched pasta and rich sauces inspired by traditional Italian kitchens.',
    emoji: '🍝',
    donut: 'conic-gradient(#22C55E 0deg 200deg, var(--primary) 200deg 270deg, #1E293B 270deg 360deg)',
    donutLegend: [['#22C55E', 'Carbs'], ['var(--primary)', 'Protein'], ['#1E293B', 'Fats']],
    stats: [
      ['🍝 Avg. Carbs', '68g'],
      ['🔥 Avg. Calories', '637 kcal'],
      ['🎯 Best for', 'Carb Loading', '#FEF9C3', '#854D0E'],
    ],
    quote: '"Perfect for pre-exam carb loading. The carbonara is unmatched."',
    tabs: ['All Items', 'Pasta', 'Risotto', 'Vegan'],
    items: ['pasta-bolo', 'pasta-aglio', 'pasta-carb'],
    persIcon: '🍝',
    persTitle: 'Carb-Loading Day?',
    persDesc: "Tell us your training schedule and we'll suggest the best pasta meals for your energy needs.",
    persBtnTxt: 'Set Training Day',
  },

  zen: {
    id: 'zen',
    name: 'Zen Smoothie Bar',
    title: 'Zen\nSmoothie Bar',
    tag: 'Beverages',
    rating: '4.9',
    wait: '5 min',
    open: true,
    desc: 'Nutrient-packed smoothies and cold-press juices to refresh your mind and fuel your studies.',
    emoji: '🥤',
    donut: 'conic-gradient(#0AAFE0 0deg 90deg, #22C55E 90deg 200deg, #F59E0B 200deg 360deg)',
    donutLegend: [['#0AAFE0', 'Protein'], ['#22C55E', 'Carbs'], ['#F59E0B', 'Sugars']],
    stats: [
      ['🥤 Avg. Calories', '105 kcal'],
      ['💧 Cold Press Options', '3 drinks'],
      ['🎯 Best for', 'Brain Power', '#E0F2FE', '#0369A1'],
    ],
    quote: '"Best smoothies on campus. The blueberry protein shake is a must-try!"',
    tabs: ['All Drinks', 'Smoothies', 'Cold Press', 'Teas'],
    items: ['smoothie', 'smoothie', 'smoothie', 'smoothie', 'smoothie', 'smoothie'],
    persIcon: '🧠',
    persTitle: 'Brain Fuel Selection',
    persDesc: "Tell us your study schedule and we'll recommend the best drinks to maximize your focus.",
    persBtnTxt: 'Set Study Goals',
  },
};


// Individual food item details (used on food detail pages)
const FOODS = {
  quinoa: {
    emoji: '🍱',
    name: 'Quinoa Power Bowl with Roasted Salmon',
    storeId: 'hrb',
    portion: '450g',
    price: '₱149.00',
    priceNum: 149,
    kcal: 680,
    tags: ['🏋️ High Protein', '🌾 Gluten-Free', '🐟 Omegas'],
    protein: 35, proteinPct: 70,
    carbs: 58,   carbsPct: 55,
    fat: 24,     fatPct: 40,
    prepTime: '12-15 min',
    vegan: true,
    desc: 'A nutrient dense powerhouse featuring fluffy organic quinoa, pan seared Atlantic salmon, roasted sweet potatoes, fresh avocado, and a zesty lemon tahini dressing. Perfect for a post-workout lunch or a sustained afternoon energy boost.',
    ingredients: ['Quinoa', 'Salmon', 'Sweet Potato', 'Avocado', 'Kale', 'Tahini', 'Lemon', 'Olive Oil', 'Black Sesame Seeds'],
    allergen: 'Contains: Fish, Sesame. Prepared in a kitchen that also handles nuts, soy, and dairy.',
    insight: 'This dish is exceptionally high in Omega-3 fatty acids, which help boost concentration during lectures!',
    budget: '₱170.00',
    related: [
      { emoji: '🍹', name: 'Iced Hibiscus Tea',  cal: '45 kcal',  price: '₱109.00', id: 'smoothie' },
      { emoji: '🍲', name: 'Side Miso Soup',     cal: '90 kcal',  price: '₱59.00',  id: 'med'     },
      { emoji: '🥑', name: 'Avocado Toast',      cal: '320 kcal', price: '₱129.00', id: 'med'     },
      { emoji: '🍟', name: 'French Fries',       cal: '120 kcal', price: '₱99.00',  id: 'med'     },
    ],
  },

  chicken: {
    emoji: '🍗',
    name: 'Grilled Chicken Salad',
    storeId: 'hrb',
    portion: '380g',
    price: '₱159.00',
    priceNum: 159,
    kcal: 510,
    tags: ['🏋️ High Protein', '🥗 Low Carb', '🔥 Keto Friendly'],
    protein: 32, proteinPct: 64,
    carbs: 22,   carbsPct: 22,
    fat: 18,     fatPct: 36,
    prepTime: '10-12 min',
    vegan: false,
    desc: "Tender flame-grilled chicken breast served over a bed of mixed greens, cherry tomatoes, cucumber ribbons, and a house-made lemon herb vinaigrette. A light, satisfying meal that won't slow you down between classes.",
    ingredients: ['Chicken Breast', 'Mixed Greens', 'Cherry Tomatoes', 'Cucumber', 'Red Onion', 'Olive Oil', 'Lemon', 'Herbs'],
    allergen: 'Contains: No common allergens. May contain traces of nuts.',
    insight: 'High in lean protein and low in saturated fat — ideal for maintaining steady energy throughout long study sessions.',
    budget: '₱160.00',
    related: [
      { emoji: '🍱', name: 'Quinoa Power Bowl', cal: '420 kcal', price: '₱149.00', id: 'quinoa'  },
      { emoji: '🥤', name: 'Green Kale Detox',  cal: '90 kcal',  price: '₱129.00', id: 'smoothie' },
      { emoji: '🥦', name: 'Teriyaki Tofu',     cal: '450 kcal', price: '₱109.00', id: 'tofu'    },
      { emoji: '🍲', name: 'Side Miso Soup',    cal: '90 kcal',  price: '₱59.00',  id: 'med'     },
    ],
  },

  med: {
    emoji: '🥙',
    name: 'Mediterranean Bowl',
    storeId: 'hrb',
    portion: '320g',
    price: '₱99.00',
    priceNum: 99,
    kcal: 380,
    tags: ['🌱 Vegan', '🫒 Mediterranean', '💚 Heart Healthy'],
    protein: 12, proteinPct: 24,
    carbs: 45,   carbsPct: 45,
    fat: 14,     fatPct: 28,
    prepTime: '8-10 min',
    vegan: true,
    desc: "A vibrant bowl inspired by Mediterranean cuisine — warm falafel, roasted red peppers, kalamata olives, cherry tomatoes, and a generous dollop of hummus over a bed of quinoa and arugula, finished with a tahini drizzle.",
    ingredients: ['Falafel', 'Quinoa', 'Arugula', 'Hummus', 'Kalamata Olives', 'Roasted Peppers', 'Cherry Tomatoes', 'Tahini'],
    allergen: 'Contains: Sesame, Gluten (falafel). Suitable for vegans.',
    insight: 'Rich in plant-based protein and healthy fats. The Mediterranean diet is linked to improved cognitive function and memory.',
    budget: '₱220.00',
    related: [
      { emoji: '🍱', name: 'Quinoa Power Bowl',   cal: '420 kcal', price: '₱149.00', id: 'quinoa'   },
      { emoji: '🍗', name: 'Grilled Chicken Salad', cal: '510 kcal', price: '₱159.00', id: 'chicken'  },
      { emoji: '🥦', name: 'Teriyaki Tofu',        cal: '450 kcal', price: '₱109.00', id: 'tofu'     },
      { emoji: '🫐', name: 'Blueberry Smoothie',   cal: '180 kcal', price: '₱119.00', id: 'smoothie' },
    ],
  },

  tofu: {
    emoji: '🥦',
    name: 'Teriyaki Tofu Stir-fry',
    storeId: 'hrb',
    portion: '400g',
    price: '₱109.00',
    priceNum: 109,
    kcal: 450,
    tags: ['🌱 Vegan', '🥢 Asian Style', '💪 Plant Protein'],
    protein: 20, proteinPct: 40,
    carbs: 65,   carbsPct: 65,
    fat: 10,     fatPct: 20,
    prepTime: '10 min',
    vegan: true,
    desc: 'Golden pan-fried tofu cubes glazed in a rich house teriyaki sauce, wok-tossed with broccoli florets, snap peas, shredded carrots, and sesame seeds, served over steamed jasmine rice.',
    ingredients: ['Firm Tofu', 'Jasmine Rice', 'Broccoli', 'Snap Peas', 'Carrots', 'Teriyaki Sauce', 'Sesame Seeds', 'Ginger'],
    allergen: 'Contains: Soy, Sesame, Gluten (teriyaki sauce). Fully vegan.',
    insight: 'An excellent plant-based protein source. Tofu provides all essential amino acids and supports muscle recovery post-exercise.',
    budget: '₱210.00',
    related: [
      { emoji: '🍱', name: 'Quinoa Power Bowl',    cal: '420 kcal', price: '₱149.00', id: 'quinoa'   },
      { emoji: '🥙', name: 'Mediterranean Bowl',   cal: '380 kcal', price: '₱99.00',  id: 'med'      },
      { emoji: '🍹', name: 'Iced Hibiscus Tea',    cal: '45 kcal',  price: '₱109.00', id: 'smoothie' },
      { emoji: '🐟', name: 'Roasted Salmon Fillet', cal: '480 kcal', price: '₱179.00', id: 'salmon'   },
    ],
  },

  steak: {
    emoji: '🥩',
    name: 'Steak & Sweet Potato',
    storeId: 'hrb',
    portion: '500g',
    price: '₱149.00',
    priceNum: 149,
    kcal: 620,
    tags: ['💪 High Protein', '🔥 High Calorie', '🥩 Grill'],
    protein: 45, proteinPct: 90,
    carbs: 40,   carbsPct: 40,
    fat: 22,     fatPct: 44,
    prepTime: '15-18 min',
    vegan: false,
    desc: "A premium campus dining experience — 180g of grilled sirloin steak served alongside caramelized sweet potato wedges, steamed green beans, and a house chimichurri sauce. Fuel for the long haul.",
    ingredients: ['Sirloin Steak', 'Sweet Potato', 'Green Beans', 'Chimichurri', 'Garlic', 'Rosemary', 'Olive Oil', 'Sea Salt'],
    allergen: 'Contains: No common allergens. Cooked on a shared grill with fish and poultry.',
    insight: 'Rich in creatine and complete proteins that directly support muscle synthesis and explosive energy output.',
    budget: '₱170.00',
    related: [
      { emoji: '🐟', name: 'Roasted Salmon Fillet', cal: '480 kcal', price: '₱179.00', id: 'salmon'   },
      { emoji: '🍗', name: 'Grilled Chicken Salad', cal: '510 kcal', price: '₱159.00', id: 'chicken'  },
      { emoji: '🥤', name: 'Blueberry Smoothie',    cal: '180 kcal', price: '₱119.00', id: 'smoothie' },
      { emoji: '🥦', name: 'Teriyaki Tofu Stir-fry', cal: '450 kcal', price: '₱109.00', id: 'tofu'    },
    ],
  },

  salmon: {
    emoji: '🐟',
    name: 'Roasted Salmon Fillet',
    storeId: 'hrb',
    portion: '420g',
    price: '₱179.00',
    priceNum: 179,
    kcal: 480,
    tags: ['🐟 Omega-3 Rich', '🌾 Gluten-Free', '🧠 Brain Food'],
    protein: 34, proteinPct: 68,
    carbs: 5,    carbsPct: 10,
    fat: 28,     fatPct: 56,
    prepTime: '14-16 min',
    vegan: false,
    desc: "Oven-roasted Atlantic salmon fillet seasoned with lemon zest and fresh herbs, served over wilted spinach with roasted cherry tomatoes and a side of herbed cauliflower rice. Clean, light, and deeply nutritious.",
    ingredients: ['Atlantic Salmon', 'Cauliflower Rice', 'Spinach', 'Cherry Tomatoes', 'Lemon', 'Dill', 'Capers', 'Olive Oil'],
    allergen: 'Contains: Fish. Prepared separately from other allergens.',
    insight: 'Exceptionally rich in DHA — the Omega-3 fatty acid most directly linked to brain function, memory retention, and exam performance.',
    budget: '₱140.00',
    related: [
      { emoji: '🍱', name: 'Quinoa Power Bowl',   cal: '420 kcal', price: '₱149.00', id: 'quinoa'   },
      { emoji: '🥩', name: 'Steak & Sweet Potato', cal: '620 kcal', price: '₱149.00', id: 'steak'    },
      { emoji: '🥙', name: 'Mediterranean Bowl',  cal: '380 kcal', price: '₱99.00',  id: 'med'      },
      { emoji: '🍹', name: 'Iced Hibiscus Tea',   cal: '45 kcal',  price: '₱109.00', id: 'smoothie' },
    ],
  },

  smoothie: {
    emoji: '🫐',
    name: 'Blueberry Protein Smoothie',
    storeId: 'zen',
    portion: '500ml',
    price: '₱119.00',
    priceNum: 119,
    kcal: 180,
    tags: ['🫐 Antioxidants', '💪 Protein Boost', '🧠 Brain Power'],
    protein: 20, proteinPct: 40,
    carbs: 15,   carbsPct: 30,
    fat: 4,      fatPct: 8,
    prepTime: '3-5 min',
    vegan: true,
    desc: "A creamy blend of wild blueberries, banana, plant-based protein powder, almond milk, and a touch of honey. Packed with antioxidants and protein to kickstart your morning or power your afternoon study session.",
    ingredients: ['Wild Blueberries', 'Banana', 'Plant Protein Powder', 'Almond Milk', 'Honey', 'Chia Seeds', 'Spinach'],
    allergen: 'Contains: Tree Nuts (almond milk). Suitable for vegans.',
    insight: 'Blueberries are one of the highest antioxidant foods — linked to improved memory and reduced mental fatigue during long study sessions.',
    budget: '₱200.00',
    related: [
      { emoji: '🍱', name: 'Quinoa Power Bowl',   cal: '420 kcal', price: '₱149.00', id: 'quinoa'   },
      { emoji: '🍗', name: 'Grilled Chicken Salad', cal: '510 kcal', price: '₱159.00', id: 'chicken'  },
      { emoji: '🥝', name: 'Green Kale Detox',    cal: '90 kcal',  price: '₱129.00', id: 'smoothie' },
      { emoji: '🥭', name: 'Mango Sunrise Shake', cal: '200 kcal', price: '₱99.00',  id: 'smoothie' },
    ],
  },

  eggs: {
    emoji: '🥚',
    name: 'Hard-Boiled Eggs (2pcs)',
    storeId: 'hrb',
    portion: '120g',
    price: '₱25.00',
    priceNum: 25,
    kcal: 140,
    tags: ['💪 Protein Rich', '🥚 Fresh Daily', '⚡ Quick Snack'],
    protein: 12, proteinPct: 24,
    carbs: 1,    carbsPct: 2,
    fat: 9,      fatPct: 18,
    prepTime: '5 min',
    vegan: false,
    desc: "Farm-fresh hard-boiled eggs, perfectly cooked to a creamy yolk. A simple, affordable, high-protein snack for students on the go. Served with a small sachet of sea salt and cracked pepper.",
    ingredients: ['Free-Range Eggs', 'Sea Salt', 'Cracked Pepper'],
    allergen: 'Contains: Eggs. Free from other common allergens.',
    insight: "Eggs are one of the most bioavailable sources of protein. Each egg provides 6g of complete protein with all essential amino acids.",
    budget: '₱290.00',
    related: [
      { emoji: '🍱', name: 'Quinoa Power Bowl',   cal: '420 kcal', price: '₱149.00', id: 'quinoa'   },
      { emoji: '🍗', name: 'Grilled Chicken Salad', cal: '510 kcal', price: '₱159.00', id: 'chicken'  },
      { emoji: '🫐', name: 'Blueberry Smoothie',  cal: '180 kcal', price: '₱119.00', id: 'smoothie' },
      { emoji: '🥦', name: 'Teriyaki Tofu',       cal: '450 kcal', price: '₱109.00', id: 'tofu'     },
    ],
  },

  'pasta-bolo': {
    emoji: '🍝',
    name: 'Spaghetti Bolognese',
    storeId: 'pasta',
    portion: '350g',
    price: '₱149.00',
    priceNum: 149,
    kcal: 640,
    tags: ['🍝 Classic Italian', '🥩 Meaty', '🔥 High Energy'],
    protein: 28, proteinPct: 56,
    carbs: 72,   carbsPct: 72,
    fat: 18,     fatPct: 36,
    prepTime: '10-12 min',
    vegan: false,
    desc: "Classic spaghetti with a rich slow-cooked Bolognese sauce made from ground beef, San Marzano tomatoes, fresh basil, and a touch of red wine. Finished with freshly grated Parmigiano-Reggiano.",
    ingredients: ['Spaghetti', 'Ground Beef', 'San Marzano Tomatoes', 'Basil', 'Red Wine', 'Onion', 'Garlic', 'Parmesan'],
    allergen: 'Contains: Gluten, Dairy, Eggs. Not suitable for vegetarians.',
    insight: 'A great carb-loading meal before exams or training. The combination of complex carbs and protein provides sustained energy.',
    budget: '₱170.00',
    related: [
      { emoji: '🍜', name: 'Aglio e Olio',       cal: '580 kcal', price: '₱139.00', id: 'pasta-aglio' },
      { emoji: '🫕', name: 'Chicken Carbonara',  cal: '690 kcal', price: '₱159.00', id: 'pasta-carb'  },
      { emoji: '🫐', name: 'Blueberry Smoothie', cal: '180 kcal', price: '₱119.00', id: 'smoothie'    },
      { emoji: '🍗', name: 'Grilled Chicken',    cal: '510 kcal', price: '₱159.00', id: 'chicken'     },
    ],
  },

  'pasta-aglio': {
    emoji: '🍜',
    name: 'Aglio e Olio',
    storeId: 'pasta',
    portion: '300g',
    price: '₱139.00',
    priceNum: 139,
    kcal: 580,
    tags: ['🌱 Vegan', '🫒 Olive Oil Rich', '🍝 Classic'],
    protein: 12, proteinPct: 24,
    carbs: 68,   carbsPct: 68,
    fat: 20,     fatPct: 40,
    prepTime: '8-10 min',
    vegan: true,
    desc: "A simple yet elegant pasta dish featuring perfectly al dente spaghetti tossed in fragrant garlic-infused extra-virgin olive oil, fresh chili flakes, and a generous handful of flat-leaf parsley. Less is more.",
    ingredients: ['Spaghetti', 'Extra-Virgin Olive Oil', 'Garlic', 'Chili Flakes', 'Flat-Leaf Parsley', 'Sea Salt'],
    allergen: 'Contains: Gluten. Suitable for vegans.',
    insight: "One of Italy's simplest dishes, proving that great ingredients need little intervention. High in heart-healthy monounsaturated fats.",
    budget: '₱180.00',
    related: [
      { emoji: '🍝', name: 'Spaghetti Bolognese', cal: '640 kcal', price: '₱149.00', id: 'pasta-bolo' },
      { emoji: '🫕', name: 'Chicken Carbonara',   cal: '690 kcal', price: '₱159.00', id: 'pasta-carb' },
      { emoji: '🥙', name: 'Mediterranean Bowl',  cal: '380 kcal', price: '₱99.00',  id: 'med'        },
      { emoji: '🥦', name: 'Teriyaki Tofu',       cal: '450 kcal', price: '₱109.00', id: 'tofu'       },
    ],
  },

  'pasta-carb': {
    emoji: '🫕',
    name: 'Chicken Carbonara',
    storeId: 'pasta',
    portion: '380g',
    price: '₱159.00',
    priceNum: 159,
    kcal: 690,
    tags: ['🍝 Creamy', '🍗 Chicken', '🥚 Egg-Based'],
    protein: 35, proteinPct: 70,
    carbs: 65,   carbsPct: 65,
    fat: 22,     fatPct: 44,
    prepTime: '12-14 min',
    vegan: false,
    desc: "Velvety carbonara sauce made from fresh egg yolks and Pecorino Romano, tossed with al dente spaghetti and grilled chicken breast strips. A rich, satisfying pasta that doubles as a muscle-building meal.",
    ingredients: ['Spaghetti', 'Chicken Breast', 'Egg Yolks', 'Pecorino Romano', 'Black Pepper', 'Garlic', 'Olive Oil'],
    allergen: 'Contains: Eggs, Dairy, Gluten. Not suitable for vegans.',
    insight: "High in both protein and complex carbohydrates — an ideal post-workout recovery meal that repairs muscle while replenishing glycogen stores.",
    budget: '₱160.00',
    related: [
      { emoji: '🍝', name: 'Spaghetti Bolognese', cal: '640 kcal', price: '₱149.00', id: 'pasta-bolo'  },
      { emoji: '🍜', name: 'Aglio e Olio',        cal: '580 kcal', price: '₱139.00', id: 'pasta-aglio' },
      { emoji: '🥩', name: 'Steak & Sweet Potato', cal: '620 kcal', price: '₱149.00', id: 'steak'      },
      { emoji: '🫐', name: 'Blueberry Smoothie',  cal: '180 kcal', price: '₱119.00', id: 'smoothie'    },
    ],
  },
};


// Menu item cards shown in the store grid
const STORE_ITEMS = {
  hrb: [
    { id: 'quinoa',  emoji: '🍱', name: 'Quinoa Power Rice Bowl',  type: 'Salad • Standard Portion', protein: 35, carbs: 58, energy: 420, price: '₱149.00', veg: true,  bg: 'linear-gradient(135deg,#F0FDF4,#DCFCE7)' },
    { id: 'chicken', emoji: '🍗', name: 'Grilled Chicken Salad',   type: 'Salad • Standard Portion', protein: 32, carbs: 22, energy: 510, price: '₱159.00', veg: false, bg: 'linear-gradient(135deg,#FFF7ED,#FED7AA)' },
    { id: 'med',     emoji: '🥙', name: 'Mediterranean Bowl',      type: 'Snack • Standard Portion', protein: 12, carbs: 45, energy: 380, price: '₱99.00',  veg: true,  bg: 'linear-gradient(135deg,#F0F9FF,#DBEAFE)' },
    { id: 'tofu',    emoji: '🥦', name: 'Teriyaki Tofu Stir-fry',  type: 'Asian • Standard Portion', protein: 20, carbs: 65, energy: 450, price: '₱109.00', veg: true,  bg: 'linear-gradient(135deg,#F0FDF4,#BBF7D0)' },
    { id: 'steak',   emoji: '🥩', name: 'Steak & Sweet Potato',    type: 'Grill • Standard Portion', protein: 45, carbs: 40, energy: 620, price: '₱149.00', veg: false, bg: 'linear-gradient(135deg,#FFF7ED,#FED7AA)' },
    { id: 'salmon',  emoji: '🐟', name: 'Roasted Salmon Fillet',   type: 'Grill • Standard Portion', protein: 34, carbs: 5,  energy: 480, price: '₱179.00', veg: false, bg: 'linear-gradient(135deg,#FFF1F2,#FFE4E6)' },
  ],

  pp: [
    { id: 'steak',   emoji: '🥩', name: 'Steak & Protein Rice',    type: 'Grill • Large Portion',    protein: 55, carbs: 48, energy: 720, price: '₱189.00', veg: false, bg: 'linear-gradient(135deg,#FFF7ED,#FED7AA)' },
    { id: 'chicken', emoji: '🍗', name: 'Grilled Chicken Plate',   type: 'Grill • Standard Portion', protein: 48, carbs: 30, energy: 580, price: '₱169.00', veg: false, bg: 'linear-gradient(135deg,#F0FDF4,#DCFCE7)' },
    { id: 'salmon',  emoji: '🐟', name: 'Salmon Power Plate',      type: 'Grill • Standard Portion', protein: 42, carbs: 10, energy: 520, price: '₱199.00', veg: false, bg: 'linear-gradient(135deg,#FFF1F2,#FFE4E6)' },
    { id: 'tofu',    emoji: '🧆', name: 'Tofu Protein Bowl',       type: 'Vegan • Standard Portion', protein: 28, carbs: 35, energy: 420, price: '₱129.00', veg: true,  bg: 'linear-gradient(135deg,#F0FDF4,#BBF7D0)' },
    { id: 'quinoa',  emoji: '🫙', name: 'Egg White & Quinoa',      type: 'Breakfast • Standard',     protein: 38, carbs: 42, energy: 460, price: '₱159.00', veg: false, bg: 'linear-gradient(135deg,#EFF6FF,#DBEAFE)' },
    { id: 'eggs',    emoji: '🥚', name: 'Hard-Boiled Eggs (3pcs)', type: 'Snack • Standard',         protein: 18, carbs: 2,  energy: 210, price: '₱49.00',  veg: false, bg: 'linear-gradient(135deg,#FEF9C3,#FEF08A)' },
  ],

  pasta: [
    { id: 'pasta-bolo',  emoji: '🍝', name: 'Spaghetti Bolognese', type: 'Pasta • Standard Portion', protein: 28, carbs: 72, energy: 640, price: '₱149.00', veg: false, bg: 'linear-gradient(135deg,#FEF9C3,#FEF08A)' },
    { id: 'pasta-aglio', emoji: '🍜', name: 'Aglio e Olio',        type: 'Pasta • Standard Portion', protein: 12, carbs: 68, energy: 580, price: '₱139.00', veg: true,  bg: 'linear-gradient(135deg,#F0FDF4,#DCFCE7)' },
    { id: 'pasta-carb',  emoji: '🫕', name: 'Chicken Carbonara',   type: 'Pasta • Standard Portion', protein: 35, carbs: 65, energy: 690, price: '₱159.00', veg: false, bg: 'linear-gradient(135deg,#FFF7ED,#FED7AA)' },
  ],

  zen: [
    { id: 'smoothie', emoji: '🫐', name: 'Blueberry Protein Smoothie', type: 'Smoothie • 500ml',    protein: 20, carbs: 15, energy: 180, price: '₱119.00', veg: true, bg: 'linear-gradient(135deg,#EDE9FE,#DDD6FE)' },
    { id: 'smoothie', emoji: '🍓', name: 'Iced Hibiscus Tea',          type: 'Tea • 400ml',         protein: 0,  carbs: 12, energy: 45,  price: '₱109.00', veg: true, bg: 'linear-gradient(135deg,#FFF1F2,#FFE4E6)' },
    { id: 'smoothie', emoji: '🥝', name: 'Green Kale Detox',           type: 'Cold Press • 350ml',  protein: 4,  carbs: 18, energy: 90,  price: '₱129.00', veg: true, bg: 'linear-gradient(135deg,#F0FDF4,#DCFCE7)' },
    { id: 'smoothie', emoji: '🥭', name: 'Mango Sunrise Shake',        type: 'Smoothie • 500ml',    protein: 8,  carbs: 36, energy: 200, price: '₱99.00',  veg: true, bg: 'linear-gradient(135deg,#FFF7ED,#FED7AA)' },
    { id: 'smoothie', emoji: '🧊', name: 'Coconut Cold Brew',          type: 'Cold Press • 350ml',  protein: 2,  carbs: 8,  energy: 60,  price: '₱89.00',  veg: true, bg: 'linear-gradient(135deg,#F0FBFF,#E0F2FE)' },
    { id: 'smoothie', emoji: '🍋', name: 'Lemon Ginger Zinger',        type: 'Tea • 350ml',         protein: 1,  carbs: 14, energy: 55,  price: '₱79.00',  veg: true, bg: 'linear-gradient(135deg,#FEF9C3,#FEF08A)' },
  ],
};
